apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coursesapi
  template:
    metadata:
      labels:
        app: coursesapi
    spec:
      containers:
      - name: coursesapi
        image: mycontainerregistry200.azurecr.io/coursesapi:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__CoursesApiContext
          value: "Server=sqldata;Database=CoursesDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False"
        - name: MessageBroker__Host
          value: "amqp://Nedas:test@rabbitmq:5672"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coursesapi
spec:
  selector:
    app: coursesapi
  ports:
  - protocol: TCP
    port: 5082
    targetPort: 8080