version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5251:8080"

  studentsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__StudentsAPIContext=Server=sqldata;Database=StudentDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
      - MessageBroker__Host=amqp://Nedas:test@rabbitmq:5672 
    ports:
      - "5081:8080"

  coursesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__CoursesApiContext=Server=sqldata;Database=CoursesDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
      - MessageBroker__Host=amqp://Nedas:test@rabbitmq:5672 
    ports:
      - "5082:8080"
 
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5088:8080"

  rabbitmq:
    environment:
    - RABBITMQ_DEFAULT_USER=Nedas
    - RABBITMQ_DEFAULT_PASS=test
    ports:
    - "15672:15672"
    - "5672:5672"

  sqldata:
    environment:
      - SA_PASSWORD=My!P@ssw0rd1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - lab2-sqldata:/var/opt/mssql

volumes:
  lab2-sqldata:
    external: false


