apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldata
  template:
    metadata:
      labels:
        app: sqldata
    spec:
      containers:
      - name: sqldata
        image: mycontainerregistry200.azurecr.io/sqldata:latest
        env:
        - name: SA_PASSWORD
          value: "My!P@ssw0rd1"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: sqldata
spec:
  selector:
    app: sqldata
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433